@echo off
REM ============================================================================
REM dashboards.bat
REM
REM Refresh all NON-eToro data feeds + regenerate every local dashboard
REM + copy ALL dashboards to Google Drive Upload as standalone HTML.
REM
REM This does NOT touch eToro_Master.xlsx or recompute valuations - run
REM `eToro.bat` first if those need refreshing.
REM
REM Steps:
REM   1. Sync data feeds:    calendar, gmail, vault (health),
REM                          earnings + dividends, T212, macro, finances,
REM                          stock exposure
REM   2. Regenerate dashboards: T212, macro, finances, exposure
REM                            (eToro_dashboard.html is regenerated by eToro.bat)
REM   3. Build standalone copies + copy ALL to C:\Users\Neil\My Drive\Upload\
REM
REM Total time: ~5-7 minutes (most of it is the eToro Hourly / valuation
REM refresh inside run_combined.py).
REM ============================================================================

setlocal
cd /d "%~dp0"

if not exist logs mkdir logs

set PYTHON=
if exist "D:\Anaconda\python.exe"               set PYTHON=D:\Anaconda\python.exe
if exist "C:\Anaconda3\python.exe"              set PYTHON=C:\Anaconda3\python.exe
if exist "C:\ProgramData\Anaconda3\python.exe"  set PYTHON=C:\ProgramData\Anaconda3\python.exe
if "%PYTHON%"=="" (
    where python >nul 2>&1
    if not errorlevel 1 (set PYTHON=python) else (
        echo ERROR: Python not found. & exit /b 1
    )
)

echo.
echo ============================================================
echo   dashboards.bat - refresh data feeds + all dashboards
echo   %DATE% %TIME%
echo ============================================================

echo.
echo [1/9] Calendar sync ...
"%PYTHON%" scripts\sync_calendar.py

echo.
echo [2/9] Gmail sync ...
"%PYTHON%" scripts\sync_gmail.py

echo.
echo [3/9] Vault health notes sync ...
"%PYTHON%" scripts\sync_vault.py

echo.
echo [4/9] Earnings + dividends sync ...
"%PYTHON%" scripts\sync_earnings_dividends.py

echo.
echo [5/9] Combined (T212) dashboard ...
"%PYTHON%" run_combined.py

echo.
echo [6/9] Macro dashboard ...
"%PYTHON%" run_macro.py

echo.
echo [7/9] Stock exposure ^(consolidated across brokers + fund decomposition^) ...
"%PYTHON%" scripts\sync_stock_exposure.py
"%PYTHON%" scripts\generate_exposure_dashboard.py

echo.
echo [8/9] Finances dashboard ^(Google Sheets pull + render^) ...
"%PYTHON%" scripts\sync_finances.py
"%PYTHON%" scripts\generate_finances_dashboard.py

echo.
echo [9/9] Build standalone dashboards + copy ALL to Google Drive Upload ...
"%PYTHON%" scripts\build_static_dashboards.py

echo.
echo ============================================================
echo   dashboards.bat - DONE
echo   Local:  C:\Users\Neil\ClaudeCode\eToro\dashboards\
echo   Drive:  C:\Users\Neil\My Drive\Upload\
echo ============================================================
echo.

endlocal
exit /b 0
